language: php
php:
  - "7.0"
 # list any PHP version you want to test against
 
script:
- php index.php



# Matriz de sistemas operativos sobre los que queremos lanzar el CI
os:
  - linux
  - osx

notifications:
 - email:false



